### ISSUE TITLE
enable container builder API during infra setup

### ISSUE THREAD

**Issue by VikramTiwari** [tpryan/whack_a_pod#3]
Otherwise, it fails on a new project at `make build` step

**Comment by tpryan** [comment]
Is that not covered in the [README.MD Section](https://github.com/tpryan/whack_a_pod/blob/master/README.md#create-and-configure-gcp-project): 
Create and configure GCP project

**Create Project in Cloud Console**
* Navigate to Compute Engine (to activate Compute Engine service)
* Navigate to the API Library and activate Container Builder API

**Comment by VikramTiwari** [comment]
Ah! I guess I missed that while retrying on a yet another totally new project. That works. Closing.
